### ISSUE TITLE
Translucent - 2.0.0

### ISSUE THREAD

**Issue by micahkendall** [txpipe/translucent#4]
# todo:
- [] - add deprecation tags to current endpoints/types for refactoring, add new versions.
- [ ] - import types from CML instead of defining our own
- [ ] - stop using "Unit" to refer to assets
- [ ] - align with other Haskell or Rust libraries
- [ ] - Drop CML?

**Comment by micahkendall** [comment]
Types from CML are similar or equivalent to much of the types defined in types.ts. Good to switch over to improve accuracy and reduce maintenance.
